//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.269
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWisteria.StudiesOfOpenTK.SimpleCloo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWisteria.StudiesOfOpenTK.SimpleCloo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   #version 330
        ///
        /////! input: particle data
        ///in Particle
        ///{
        ///	//! center position
        ///	vec4 X;
        ///
        ///	//! color
        ///	vec4 Color;
        ///} particleGeometry;
        ///
        /////! output: color
        ///out vec4 outColor;
        ///
        ///
        /////! input: projection matrix
        ///uniform mat4 projection;
        ///
        /////! input: view maxrix (camera)
        ///uniform mat4 view;
        ///
        /////! input: strength of ambient 
        ///uniform float ambient;
        ///
        /////! input: direction vector of light
        ///uniform vec3 sunLight;
        ///
        /////! input: strength of light from camera
        ///uniform float cameraLight;
        ///
        /////! input: position  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string point_fragment {
            get {
                return ResourceManager.GetString("point_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #version 330
        ///
        ///layout(points) in; 
        ///layout(points, max_vertices=1) out;
        ///
        /////! input: view matrix (camera)
        ///uniform mat4 view;
        ///
        /////! input: projection matrix
        ///uniform mat4 projection;
        ///
        /////! input: rendering size of particle
        ///uniform float size;
        ///
        /////! input: particle data
        ///in Particle
        ///{
        ///	//! center position
        ///	vec4 X;
        ///
        ///	//! length of a edge
        ///	float D;
        ///
        ///	//! color
        ///	vec4 Color;
        ///} particleVertex[];
        ///
        /////! output: particle data
        ///out Particle
        ///{
        ///	//! center position
        ///	vec4 X;
        ///
        ///	//! color
        ///	vec4 Colo [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string point_geometry {
            get {
                return ResourceManager.GetString("point_geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #version 330
        ///
        /////! input: position of particle
        ///in vec3 particleX;
        ///
        /////! input: color of particle
        ///in vec4 particleColor;
        ///
        /////! input: length of a edge of particle
        ///in float particleD;
        ///
        /////! output: particle data
        ///out Particle
        ///{
        ///	//! center position
        ///	vec4 X;
        ///
        ///	//! length of a edge
        ///	float D;
        ///
        ///	//! color
        ///	vec4 Color;
        ///} particleVertex;
        ///
        /////! entry point
        ///void main()
        ///{
        ///	//! set position of particle
        ///	particleVertex.X = vec4(particleX, 1.0);
        ///
        ///	//! set size of particle
        ///	particleVertex.D = part [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string point_vertex {
            get {
                return ResourceManager.GetString("point_vertex", resourceCulture);
            }
        }
    }
}
