//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.269
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWisteria.StudiesOfOpenTK.ObjectiveTK.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWisteria.StudiesOfOpenTK.ObjectiveTK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   #version 330
        ///
        /////! output: color of line
        ///in vec4 linecolor;
        ///
        /////! output: color
        ///out vec4 outColor;
        ///
        ///
        /////! input: strength of ambient 
        ///uniform float ambient;
        ///
        /////! input: direction vector of light
        ///uniform vec3 light;
        ///
        /////! entry point
        ///void main()
        ///{
        ///	// set color
        ///	outColor = linecolor;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lookat_fragment {
            get {
                return ResourceManager.GetString("lookat_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #version 330
        ///
        ///layout(points) in; 
        ///layout(lines_strip, max_vertices=24) out;
        ///
        /////! input: view (camera)
        ///uniform mat4 view;
        ///
        /////! input: projection matrix
        ///uniform mat4 projection;
        ///
        /////! input: position where I look at
        ///in vec3 lookatVertex;
        ///
        /////! output: color of line
        ///out vec4 linecolor;
        ///
        ///
        /////! projection and model matrix
        ///mat4 projectionView;
        ///
        /////! Draw a line
        ////*!
        ///	\param p0 stard position of vertex of this line
        ///	\param p1 end position of vertex of this line
        ///	\param color color of this line        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lookat_geometry {
            get {
                return ResourceManager.GetString("lookat_geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #version 330
        ///
        /////! input: position where I look at
        ///in vec3 lookat;
        ///
        /////! output: position where I look at
        ///out vec4 lookatVertex;
        ///
        /////! entry point
        ///void main()
        ///{
        ///	lookatVertex = vec4(lookat, 2.0f);
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lookat_vertex {
            get {
                return ResourceManager.GetString("lookat_vertex", resourceCulture);
            }
        }
    }
}
